local function restartUI(withMsg)
  --SendUIMessage({ source = "cool-nui", app = "main", action = "restart" });
  SendUIMessage({ app = "hud", data = { display = false }, source = "cool-nui" })
  if withMsg then
    TriggerEvent("DoLongHudText", "You can also use 'ui-r' as a shorter version to restart!")
  end
  TriggerScreenblurFadeOut(100.0)
  TriggerEvent('closeInventoryGui')
  TriggerEvent('arp-banking:ResetUI')
  TriggerEvent('arp-radio:ResetUI')
  TriggerEvent('arp-menu:ResetUI')
  TriggerEvent('arp-interact:ResetUI')
  TriggerEvent('arp-mdt:ResetUI')
  TriggerEvent('arp-ui:restartUI')
  TriggerEvent('menu:menuexit')
  TriggerEvent('clothing:close')
  exports['arp-interface']:showInteraction("Restarting UI .")
  Wait(1000)
  exports['arp-interface']:showInteraction("Restarting UI ..")
  Wait(1000)
  exports['arp-interface']:showInteraction("Restarting UI ...")
  Wait(1000)
  exports['arp-interface']:showInteraction("UI Successfully Restarted")
  Wait(1000)
  exports['arp-interface']:hideInteraction()
  SendUIMessage({ app = "hud", data = { display = true }, source = "cool-nui" })
  --TriggerEvent("cool-hud:initHud")
  initHud()
  TriggerEvent("cool-hud:restarted")
  local cj = exports["police"]:getCurrentJob()
end
RegisterCommand("cool-hud:restart", function() restartUI(true) end, false)
RegisterCommand("ui-r", function() restartUI() end, false)
RegisterNetEvent("cool-hud:server-restart")
AddEventHandler("cool-hud:server-restart", restartUI)

RegisterCommand("testui", function()
  SendUIMessage({ app = "hud", data = { display = false, health = 100 }, source = "cool-nui" })
  Wait(5000)
  SendUIMessage({ app = "hud", data = { display = true, health = 50 }, source = "cool-nui" })
end)