local function restartUI(withMsg)
  SendUIMessage({ source = "bd-nui", app = "main", action = "restart" });
  if withMsg then
    TriggerEvent("DoLongHudText", "You can also use 'ui-r' as a shorter version to restart!")
  end
  TriggerScreenblurFadeOut(100.0)
  TriggerEvent('closeInventoryGui')
  TriggerEvent('bd-banking:ResetUI')
  TriggerEvent('bd-radio:ResetUI')
  TriggerEvent('bd-menu:ResetUI')
  TriggerEvent('bd-interact:ResetUI')
  TriggerEvent('bd-mdt:ResetUI')
  TriggerEvent('bd-ui:restartUI')
  TriggerEvent('menu:menuexit')
  TriggerEvent('clothing:close')
  exports['bd-interface']:showInteraction("Restarting UI .")
  Wait(1000)
  exports['bd-interface']:showInteraction("Restarting UI ..")
  Wait(1000)
  exports['bd-interface']:showInteraction("Restarting UI ...")
  Wait(1000)
  exports['bd-interface']:showInteraction("UI Successfully Restarted")
  Wait(1000)
  exports['bd-interface']:hideInteraction()
  --TriggerEvent("bd-hud:initHud")
  initHud()
  TriggerEvent("bd-hud:restarted")
  SendUIMessage({ app = "hud", data = { display = true }, source = "bd-nui" })
  local cj = exports["police"]:getCurrentJob()
end
RegisterCommand("bd-hud:restart", function() restartUI(true) end, false)
RegisterCommand("ui-r", function() restartUI() end, false)
RegisterNetEvent("bd-hud:server-restart")
AddEventHandler("bd-hud:server-restart", restartUI)